<a href="https://colab.research.google.com/github/yeyevtushenko/AI/blob/Lesson25.03.2024/Lesson25_03_2024_AI_P_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпорт модулів

In [3]:
import torch
import numpy as np

# Завдання 1

Перегляньте інформацію про доступні процесори, та виведіть про них інформацію

In [4]:
print(torch.cuda.is_available())

if torch.cuda.is_available():
    print(torch.cuda.device_count())
    print(torch.cuda.get_device_name(0))

tensor = torch.tensor([1, 2, 3])
print(tensor.device)

True
1
Tesla T4
cpu


# Завдання 2
Підключіть colab до процесора GPU, та знову виведіть інформацію про доступні процесори

In [5]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

tensor = torch.tensor([1, 2, 3])
tensor = tensor.to(device)

tensor

tensor([1, 2, 3], device='cuda:0')

In [6]:
device

device(type='cuda')

In [7]:
tensor = torch.tensor([1, 2, 3], device=device)
tensor

tensor([1, 2, 3], device='cuda:0')

# Завдання 3
Створіть випадковий тензор розміру (2, 3). Виведіть інформацію про його:

* розмір
* тип даних
* процесор
* наявність градієнта

In [8]:
tensor = torch.randn(2, 3)

print(tensor.shape)
print(tensor.dtype)
print(tensor.device)
print(tensor.requires_grad)

torch.Size([2, 3])
torch.float32
cpu
False


# Завдання 4

Створіть 2 тензора розміру 100. Використовуючи лише модуль `torch` обрахуйте середьню абсолютну похибку(mae) між ними. Виведіть результат як число

In [9]:
tensor1 = torch.rand(100)
tensor2 = torch.rand(100)

mae = torch.abs(tensor1 - tensor2).mean()

print(mae.item())

0.33104023337364197


# Завдання 5

Створіть 3 випадкових тензора з розмірами:
* 32х28х28
* 16х28х28
* 64х28х28

Об'єднайте їх по першій розмірності. Результат має мати розмір 112х28х28

In [10]:
tensor1 = torch.randn(32, 28, 28)
tensor2 = torch.randn(16, 28, 28)
tensor3 = torch.randn(64, 28, 28)

result = torch.cat((tensor1, tensor2, tensor3), dim=0)

print(result)
print(result.size())

tensor([[[-0.6196,  0.8825, -0.0675,  ...,  0.7228, -0.2446,  2.8259],
         [ 0.7996, -0.4556,  0.2477,  ...,  1.2656, -0.8360, -2.4361],
         [ 0.6955,  0.5523, -0.2240,  ...,  0.3017, -0.8333,  1.6050],
         ...,
         [ 0.0413, -0.7741,  0.0572,  ...,  1.1188, -1.4262, -1.8259],
         [-0.1606, -0.3016,  0.6443,  ..., -2.5742,  1.0064, -0.0348],
         [ 0.3657, -0.0116, -1.4232,  ..., -0.6029,  1.4002, -0.8172]],

        [[ 0.6099, -0.4484, -0.4292,  ..., -1.4875,  0.2811, -0.3779],
         [ 0.3471,  0.4587,  1.2685,  ...,  0.3561, -1.9851,  2.4632],
         [ 0.2953,  0.4805, -0.3016,  ...,  0.0174,  1.1410, -0.3775],
         ...,
         [ 1.5791, -0.0678, -0.0371,  ...,  1.0684, -1.1546, -0.9660],
         [-0.8337,  0.5553, -1.1029,  ..., -0.6275, -0.5089, -0.3028],
         [-0.5590,  1.5035,  1.6443,  ..., -1.1660, -0.2314,  0.8783]],

        [[-0.5506,  1.2499, -1.0487,  ..., -1.0045, -0.1395, -2.1279],
         [ 1.1020, -2.6740,  1.0957,  ..., -0

# Завдання 6
Застосуйте метод градієнтного спуску для функції

In [11]:
def f(x):
  return x**2/3 + torch.sin(torch.pi*x)

In [12]:
device = "cuda" if torch.cuda.is_available() else "cpu"
torch.set_default_device(device)


x = torch.tensor(2.0, requires_grad=True)

learning_rate = 1e-3

for t in range(2000):
    loss = f(x)

    loss.backward()

    if t % 100 == 0:
      print(f'{loss.item()=}')

    with torch.no_grad():

      x -= learning_rate*x.grad

      x.grad = None

loss.item()=1.3333334922790527
loss.item()=-0.012307047843933105
loss.item()=-0.26274728775024414
loss.item()=-0.2934073805809021
loss.item()=-0.29722774028778076
loss.item()=-0.29771918058395386
loss.item()=-0.2977832555770874
loss.item()=-0.29779165983200073
loss.item()=-0.29779279232025146
loss.item()=-0.297792911529541
loss.item()=-0.297792911529541
loss.item()=-0.29779303073883057
loss.item()=-0.29779285192489624
loss.item()=-0.29779285192489624
loss.item()=-0.29779285192489624
loss.item()=-0.29779285192489624
loss.item()=-0.29779285192489624
loss.item()=-0.29779285192489624
loss.item()=-0.29779285192489624
loss.item()=-0.29779285192489624


# Завдання 7
Застосуйте метод градієнтного спуску для функції. Мінімум функції рівний 0

In [13]:
def f1(x, y):
  # функція Швефеля
  return  418.9829*2 - x*torch.sin(x.abs().sqrt()) - y*torch.sin(y.abs().sqrt())

def f2(x, y):
  # трьохгорбна функція
  return 2*x**2  - 1.05*x**4 + 1/6*x**6 + x*y  + y**2

def f3(x, y):
  # функція птах
  return 106.7645 + torch.sin(x)*torch.exp((1-torch.cos(y))**2) + \
  torch.cos(y)*torch.exp((1-torch.sin(x))**2) + \
  (x-y)**2

In [14]:
def gr(f, learning_rate=1e-3):
  device = "cuda" if torch.cuda.is_available() else "cpu"
  torch.set_default_device(device)

  x = torch.tensor(6.0, requires_grad=True, device=device)
  y = torch.tensor(6.0, requires_grad=True, device=device)

  for t in range(2000):
      loss = f(x,y)

      loss.backward()

      #if t % 100 == 0:
        #print(f'{loss.item()=}')

      with torch.no_grad():

        x -= learning_rate*x.grad

        x.grad = None

        y -= learning_rate*y.grad

        y.grad = None

  return x.item(), y.item(), loss.item()

In [15]:
gr(f1)

(5.579611778259277, 5.579611778259277, 830.1219482421875)

In [16]:
gr(f2,1e-3)

(-1.757537841796875, 0.9799004793167114, 0.3094998598098755)

In [17]:
gr(f3)

(6.871952533721924, 7.049767017364502, 108.27448272705078)