<a href="https://colab.research.google.com/github/yeyevtushenko/AI/blob/Lesson21.02.2024/Lesson21_02_2024_AI_H_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпортуйте модуль numpy

In [1]:
import numpy as np

#Завдання 1

Створіть масив з парними числами між 30 і 70

In [4]:
arr = np.arange(30, 71, 2)
print(arr)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


#Завдання 2
Створіть масив з 10 числами між 0(включно) та 1(не включно) див документацію

In [5]:
arr = np.linspace(0, 1, 10, endpoint=False)
print(arr)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


#Завдання 4
Напишіть функцію яка приймає матрицю розміру nxn та повертає матрицю розміру (n+2) x (n+2), на краях якої розміщенні 0.

In [10]:
n = int(input("Розмір матриці: "))

matrix = np.random.randint(1, 10, size=(n, n))

null_matrix = np.zeros((n+2, n+2))

null_matrix[1:-1, 1:-1] = matrix


print("Початкова випадкова матриця:")
print(matrix)
print("\nНова матриця з нулями на краях:")
print(null_matrix)

Розмір матриці: 5
Початкова випадкова матриця:
[[4 8 9 1 5]
 [4 7 7 6 3]
 [8 9 9 5 1]
 [9 3 4 6 7]
 [9 3 5 9 4]]

Нова матриця з нулями на краях:
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 4. 8. 9. 1. 5. 0.]
 [0. 4. 7. 7. 6. 3. 0.]
 [0. 8. 9. 9. 5. 1. 0.]
 [0. 9. 3. 4. 6. 7. 0.]
 [0. 9. 3. 5. 9. 4. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#Завдання 5
У попередьньому масиві змініть тип даних. Виведіть тип даних до та після зміни

In [12]:
print("Тип даних до зміни:")
print(matrix.dtype)
print("\nТип даних після зміни:")
print(null_matrix.dtype)

Тип даних до зміни:
int64

Тип даних після зміни:
float64


#Завдання 6
У даному масиві замініть елементи, які дорівнюють\більші\менші за var на -1

In [15]:
x = np.array([1, 5, 3, 8, 6, 5, 7, 4])
var = 5

x[x == var] = -1  # Заміна елементів, які дорівнюють var
print("Дорівнюють -1:")
print(x)
x[x > var] = -1   # Заміна елементів, які більші за var
print("Більші за -1:")
print(x)
x[x < var] = -1   # Заміна елементів, які менші за var
print("Менші за -1:")
print(x)

Дорівнюють -1:
[ 1 -1  3  8  6 -1  7  4]
Більші за -1:
[ 1 -1  3 -1 -1 -1 -1  4]
Менші за -1:
[-1 -1 -1 -1 -1 -1 -1 -1]


#Завдання 7
Замініть пропущені значення матриці(np.nan) на -1

Дивись np.isnan

In [17]:
X = np.array([[1, 2, np.nan, 4],
              [5, np.nan, np.nan, 4],
              [np.nan, 10, 11, np.nan]])
X[np.isnan(X)] = -1

print(X)

[[ 1.  2. -1.  4.]
 [ 5. -1. -1.  4.]
 [-1. 10. 11. -1.]]


#Завдання 8
Створіть матрицю розміру 4х6 з випадковими числами. Змініть її розмір на 3х8

In [21]:
print("Matrix 4*6")
matrix = np.random.random((4, 6))
print(matrix)

print("\nMatrix 3*8")
new_matrix = matrix.reshape((3, 8))
print(new_matrix)

Matrix 4*6
[[0.31185933 0.0551267  0.11723421 0.95957641 0.30779367 0.70490722]
 [0.46386089 0.73798608 0.41625072 0.97092019 0.58832643 0.09226479]
 [0.66242757 0.50138124 0.23185781 0.51403252 0.24767152 0.45839519]
 [0.99312936 0.37244271 0.76679692 0.05661521 0.89338516 0.28040445]]

Matrix 3*8
[[0.31185933 0.0551267  0.11723421 0.95957641 0.30779367 0.70490722
  0.46386089 0.73798608]
 [0.41625072 0.97092019 0.58832643 0.09226479 0.66242757 0.50138124
  0.23185781 0.51403252]
 [0.24767152 0.45839519 0.99312936 0.37244271 0.76679692 0.05661521
  0.89338516 0.28040445]]


#Завдання 9
Створіть матрицю з одиниць розміром 3х4. Знайдіть середнє арифметичне(mean) кожного стовпчика

In [22]:
matrix = np.ones((3, 4))

print("Матриця з 1:")
print(matrix)

avg = np.mean(matrix, axis=0)

print("\nСереднє арифметичне кожного стовпчика:")
print(avg)

Матриця з 1:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Середнє арифметичне кожного стовпчика:
[1. 1. 1. 1.]


#Завдання 10
Створіть випадкову матрицю розміром 5х6. Округліть значення до одного знаку після коми(np.round). Розмістіть стовпчики так, щоб значення в першому рядку були відсортовані за зростанням

In [23]:
matrix = np.random.random((5, 6))

new_matrix = np.round(matrix, decimals=1)

indices = np.argsort(new_matrix[0])

sort = new_matrix[:, indices]

print(sort)

[[0.  0.2 0.3 0.6 0.7 0.7]
 [0.2 0.9 0.  0.9 0.9 0.3]
 [0.9 0.7 0.9 0.9 0.3 0.1]
 [0.6 0.4 0.8 1.  0.7 0.2]
 [0.9 0.5 0.2 0.4 0.2 0.1]]


#Завдання 11
В даній матриці знайдіть всі елементи зі значенням між 3 і 6

Дивись документацію np.logical_and

In [25]:
X = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [9, 8, 7, 6, 5],
              [4, 3, 2, 1, 0]])

mask = np.logical_and(X > 3, X < 6)

result = X[mask]

print("Елементи між 3 і 6:")
print(result)

Елементи між 3 і 6:
[4 5 5 4]


#Завдання 12
Створіть випадкову матрицю розміру 5х6. Нормалізуйте стовпчики: від кожного елемента ставпчика відніміть мінімальне значення та поділіть результат на різницю між максимальним та мінімальним елементом.

Після цього всі значення мають бути в межах [0, 1]