<a href="https://colab.research.google.com/github/yeyevtushenko/AI/blob/Lesson21.02.2024P/module2/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпортуйте модуль numpy

In [1]:
import numpy as np

# Завдання 1
Створіть масив з елементами від 1 до 12. Виведіть розмір та тип масиву

In [14]:
array = np.arange(1, 13)
print(array)
print("Розмір:", array.size)
print("Тип:", array.dtype)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Розмір: 12
Тип: int64


# Завдання 2
Зробіть на основі попереднього масиву матрицю з 4 стовчиками. Змініть тип даних матриці на float32. Виведіть транспоновану матрицю.

#Завдання 3
Створіть матрицю 8х8 з 0 та 1 розміщеними в шаховому порядку

In [13]:
import numpy as np

array = np.zeros((8, 8))

arr[1::2, ::2] = 1
array[::2, 1::2] = 1

print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Завдання 4
Створіть випадкову матрицю 4х3. Знайдіть суму елементів в стовпчиках\рядках\усій матриці

In [11]:
matrix = np.random.rand(4, 3)
print(matrix)

[[0.72809859 0.8491355  0.34919322]
 [0.85046111 0.74249945 0.01748406]
 [0.25006772 0.62507443 0.73067886]
 [0.59968735 0.97535221 0.3208174 ]]


# Завдання 5
У попередній матриці від кожного рядка відніміть максимальний елемент цього рядка

# Завдання 6
Є дані про вагу контейнерів для перевезення на кораблі: дрібний - 5 т,  малий - 10 т, середній - 25 т, великий - 40 т. На кораблі розміщено 20 дрібних, 5 малих, 10 середніх та 4 великих контейнерів. Знайти масу вантажу.

# Завдання 7
Тепер у нас декілька кораблів. Напишіть код для обчислення вантажу на кожному кораблі.